import Head from 'next/head';
import { signOut } from 'next-auth/react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Let&apos;s build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button
        onClick={signOut}
        className="text-blue-700 font-semibold rounded-full px-5 py-1.5 transition-all hover:border-2 border border-blue-700"
      >
        Sign out
      </button>
    </div>
  );
}
